<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb7d6377ee324d8c3f56c6d308c8f812a
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb7d6377ee324d8c3f56c6d308c8f812a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb7d6377ee324d8c3f56c6d308c8f812a::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
